# Generated by Django 3.1.7 on 2021-03-04 02:46

from django.db import migrations, models
import django.db.models.deletion
import django_changed_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('zip_code', models.CharField(max_length=8)),
                ('street', models.CharField(max_length=80)),
                ('number', models.CharField(max_length=6)),
                ('complement', models.CharField(max_length=60)),
                ('district', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=2)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contact.contact')),
            ],
            options={
                'db_table': 'addresses',
            },
            bases=(django_changed_fields.ChangedFieldsMixin, models.Model),
        ),
    ]
