# Generated by Django 3.1.7 on 2021-03-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
