# Generated by Django 3.1.7 on 2021-03-04 02:46

from django.db import migrations, models
import django_changed_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('fone', models.CharField(max_length=14, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'contacts',
            },
            bases=(django_changed_fields.ChangedFieldsMixin, models.Model),
        ),
    ]
