# Generated by Django 3.1.7 on 2021-03-04 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0003_auto_20210304_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='is_global',
            new_name='is_public',
        ),
    ]
